---

- name: "package | install cloud-init package"
  package:
    name: "cloud-init"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "config | capturing cloud-init status"
  shell: cloud-init status | cut -f2 -d':'
  args:
    executable: "/bin/bash"
  register: _cloud_init_status

- name: "config | displaying cloud-init status"
  debug:
    var: _cloud_init_status['stdout']

- block:
    - name: "config | drop default cloud-init datasources and readme"
      file:
        path: "/etc/cloud/cloud.cfg.d/{{ item }}"
        state: absent
      loop:
        - "90_dpkg.cfg"
        - "README"
    - name: "config | configure main configuration cloud.cfg"
      template:
        src: "etc/cloud/cloud.cfg.j2"
        dest: "/etc/cloud/cloud.cfg"
        owner: root
        group: root
        mode: 0644
    - name: "config | configure additional modules via cloud.cfg.d"
      template:
        src: "etc/cloud/cloud.cfg.d/{{ item.filename }}.j2"
        dest: "/etc/cloud/cloud.cfg.d/{{ item.priority}}_{{ item.filename }}"
        owner: root
        group: root
        mode: 0644
        backup: yes
        trim_blocks: yes
      loop:
        - { filename: "bootcmd.cfg", priority: "10" }
        - { filename: "runcmd.cfg", priority: "10" }
        - { filename: "package.cfg", priority: "20" }
        - { filename: "ca_certificates.cfg", priority: "30" }
        - { filename: "datasource.cfg", priority: "90" }
        - { filename: "phone_home.cfg", priority: "90" }
  when: cloud_init_config
